// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQAicWGWvATan0mPPMuMvCl3NlTac2VdY',
    appId: '1:217457670566:web:dbf05637bb4eaff68e3767',
    messagingSenderId: '217457670566',
    projectId: 'tubes-pemob-3b373',
    authDomain: 'tubes-pemob-3b373.firebaseapp.com',
    storageBucket: 'tubes-pemob-3b373.firebasestorage.app',
    measurementId: 'G-14RGTP6LYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq90nid5u2Z8oRGcCvlREV3he6QGEBQPg',
    appId: '1:217457670566:android:5145038e4a8c87558e3767',
    messagingSenderId: '217457670566',
    projectId: 'tubes-pemob-3b373',
    storageBucket: 'tubes-pemob-3b373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbsWEIgEZApUCS5Qo2mzOIVK_nj5uEl0A',
    appId: '1:217457670566:ios:3516e420b821162c8e3767',
    messagingSenderId: '217457670566',
    projectId: 'tubes-pemob-3b373',
    storageBucket: 'tubes-pemob-3b373.firebasestorage.app',
    androidClientId: '217457670566-5msn1cqr9gdg0ufjb1g2985aogmg538o.apps.googleusercontent.com',
    iosClientId: '217457670566-2vc0nodi7gafkgrrqnf9qq5c77hl6r9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.findMyStuff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbsWEIgEZApUCS5Qo2mzOIVK_nj5uEl0A',
    appId: '1:217457670566:ios:3516e420b821162c8e3767',
    messagingSenderId: '217457670566',
    projectId: 'tubes-pemob-3b373',
    storageBucket: 'tubes-pemob-3b373.firebasestorage.app',
    androidClientId: '217457670566-5msn1cqr9gdg0ufjb1g2985aogmg538o.apps.googleusercontent.com',
    iosClientId: '217457670566-2vc0nodi7gafkgrrqnf9qq5c77hl6r9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.findMyStuff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQAicWGWvATan0mPPMuMvCl3NlTac2VdY',
    appId: '1:217457670566:web:7b6efd430418a1db8e3767',
    messagingSenderId: '217457670566',
    projectId: 'tubes-pemob-3b373',
    authDomain: 'tubes-pemob-3b373.firebaseapp.com',
    storageBucket: 'tubes-pemob-3b373.firebasestorage.app',
    measurementId: 'G-91EWZP28K6',
  );

}